newrelic:
  policy: Fulfiller Integration Squad policy
  refreshRate: 10000
  
gitlab:
  groupIds:
    - 121
    - 338
    - 388
    - 169
    - 394
  refreshRate: 150000
  alwaysShowLeaders: true

slideshow:
  youtube:
    - t2_W9OZcoTE #train
    - m9VO7X_q9nw #kittens!
    - 9vlavTW0rn4 #bison
    - Mk9gQcHueeE #hubble
  rate: 120000
