newrelic:
  policy: Fulfiller Integration Squad policy
  refreshRate: 10000
  
gitlab:
  groupIds:
    - 121
    - 338
    - 388
    - 169
  refreshRate: 150000
  alwaysShowLeaders: true

slideshow:
  youtube:
    - xJAc07JROGg #train
    - m9VO7X_q9nw #kittens!
    - 9vlavTW0rn4 #bison
    - GfgwU-pyOfg #africa
  rate: 120000
